"""Hard-coded data used in commands."""
# NOTE: Data in this module is hard coded because comes from
#  unstructured sources that aren't easily parsable or because the
#  nutrients are identified by name in the code.

FULL_NUTRIENT_DATA = [
    {
        "name": "Protein",
        "unit": "G",
        "fdc_ids": [1003],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 20.0,
                "amount_min": 5.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 4,
                "amount_max": 30.0,
                "amount_min": 10.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 35.0,
                "amount_min": 10.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 1.05,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 0.95,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 0.85,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 0.8,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Macronutrient"],
        "energy": 4,
    },
    {
        "name": "Lipid",
        "unit": "G",
        "fdc_ids": [1004],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 40.0,
                "amount_min": 30.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 4,
                "amount_max": 35.0,
                "amount_min": 25.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 35.0,
                "amount_min": 20.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
        ],
        "type": ["Macronutrient"],
        "energy": 9,
    },
    {
        "name": "Carbohydrate",
        "unit": "G",
        "fdc_ids": [1005],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 1,
                "amount_max": 65.0,
                "amount_min": 45.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 130.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Macronutrient"],
        "energy": 4,
    },
    {
        "name": "Alcohol",
        "unit": "G",
        "fdc_ids": [1018],
        "recommendations": [],
        "type": [],
        "energy": 7,
    },
    {
        "name": "Ash",
        "unit": "G",
        "fdc_ids": [1007],
        "recommendations": [],
        "type": [],
    },
    {
        "name": "Fiber",
        "unit": "G",
        "fdc_ids": [1079],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 14.0,
                "dri_type": "AIK",
                "sex": "B",
            },
        ],
        "type": [],
    },
    {
        "name": "Energy",
        "unit": "KCAL",
        "fdc_ids": [1008],
        "recommendations": [],
        "type": [],
    },
    {
        "name": "Water",
        "unit": "G",
        "fdc_ids": [1051],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 1300.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 1700.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 2400.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 2100.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 3300.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 2300.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 3700.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 2700.0,
                "dri_type": "AI",
                "sex": "F",
            },
        ],
        "type": [],
    },
    {
        "name": "Arsenic",
        "unit": "UG",
        "fdc_ids": [1134],
        "recommendations": [],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Boron",
        "unit": "MG",
        "fdc_ids": [1137],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 3.0,
                "dri_type": "UL",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 6.0,
                "dri_type": "UL",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 11.0,
                "dri_type": "UL",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 17.0,
                "dri_type": "UL",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 20.0,
                "dri_type": "UL",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Calcium",
        "unit": "MG",
        "fdc_ids": [1087],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 2500.0,
                "amount_min": 500.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 2500.0,
                "amount_min": 800.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 9,
                "amount_max": 2500.0,
                "amount_min": 1300.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 50,
                "age_min": 19,
                "amount_max": 2500.0,
                "amount_min": 1000.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": 2500.0,
                "amount_min": 1200.0,
                "dri_type": "AI",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Chlorine",
        "unit": "G",
        "fdc_ids": [1088],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 2.3,
                "amount_min": 1.5,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 2.9,
                "amount_min": 1.9,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 3.4,
                "amount_min": 2.3,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 50,
                "age_min": 14,
                "amount_max": 3.6,
                "amount_min": 2.3,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 70,
                "age_min": 51,
                "amount_max": 3.6,
                "amount_min": 2.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 71,
                "amount_max": 3.6,
                "amount_min": 1.8,
                "dri_type": "AI",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Chromium",
        "unit": "UG",
        "fdc_ids": [1096],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 11.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 15.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 25.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": 50,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 35.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 24.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": 50,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 25.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": None,
                "amount_min": 30.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": None,
                "amount_min": 20.0,
                "dri_type": "AI",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Copper",
        "unit": "UG",
        "fdc_ids": [1098],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 1000.0,
                "amount_min": 340.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 3000.0,
                "amount_min": 440.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 5000.0,
                "amount_min": 700.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 8000.0,
                "amount_min": 890.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 10000.0,
                "amount_min": 900.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Fluoride",
        "unit": "MG",
        "fdc_ids": [1099],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 1.3,
                "amount_min": 0.7,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 2.2,
                "amount_min": 1.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 10.0,
                "amount_min": 2.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 10.0,
                "amount_min": 3.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": 10.0,
                "amount_min": 3.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 10.0,
                "amount_min": 4.0,
                "dri_type": "AI",
                "sex": "M",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Iodine",
        "unit": "UG",
        "fdc_ids": [1100],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 200.0,
                "amount_min": 90.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 300.0,
                "amount_min": 90.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 600.0,
                "amount_min": 120.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 900.0,
                "amount_min": 150.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 1100.0,
                "amount_min": 150.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Iron",
        "unit": "MG",
        "fdc_ids": [1089],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 40.0,
                "amount_min": 7.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 40.0,
                "amount_min": 10.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 40.0,
                "amount_min": 8.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 45.0,
                "amount_min": 11.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 45.0,
                "amount_min": 15.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": 50,
                "age_min": 19,
                "amount_max": 45.0,
                "amount_min": 8.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 50,
                "age_min": 19,
                "amount_max": 45.0,
                "amount_min": 18.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": 45.0,
                "amount_min": 8.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Magnesium",
        "unit": "MG",
        "fdc_ids": [1090],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 80.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 130.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 240.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 410.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 360.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": 30,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 400.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 30,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 310.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 31,
                "amount_max": None,
                "amount_min": 420.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 31,
                "amount_max": None,
                "amount_min": 320.0,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Manganese",
        "unit": "MG",
        "fdc_ids": [1101],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 2.0,
                "amount_min": 1.2,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 3.0,
                "amount_min": 1.5,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 6.0,
                "amount_min": 1.9,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 6.0,
                "amount_min": 1.6,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 9.0,
                "amount_min": 2.2,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 9.0,
                "amount_min": 1.6,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 11.0,
                "amount_min": 2.3,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 11.0,
                "amount_min": 1.8,
                "dri_type": "AI",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Molybdenum",
        "unit": "UG",
        "fdc_ids": [1102],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 300.0,
                "amount_min": 17.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 600.0,
                "amount_min": 22.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 1100.0,
                "amount_min": 34.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 1700.0,
                "amount_min": 43.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 2000.0,
                "amount_min": 45.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Nickel",
        "unit": "MG",
        "fdc_ids": [1146],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 0.2,
                "dri_type": "UL",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 0.3,
                "dri_type": "UL",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 0.6,
                "dri_type": "UL",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 1.0,
                "dri_type": "UL",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Phosphorus",
        "unit": "MG",
        "fdc_ids": [1091],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 3000.0,
                "amount_min": 460.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 3000.0,
                "amount_min": 500.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 9,
                "amount_max": 4000.0,
                "amount_min": 1250.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 70,
                "age_min": 19,
                "amount_max": 4000.0,
                "amount_min": 700.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 71,
                "amount_max": 3000.0,
                "amount_min": 700.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Potassium",
        "unit": "G",
        "fdc_ids": [1092],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 3.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 3.8,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 4.5,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 4.7,
                "dri_type": "AI",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Selenium",
        "unit": "UG",
        "fdc_ids": [1103],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 90.0,
                "amount_min": 20.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 150.0,
                "amount_min": 30.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 280.0,
                "amount_min": 40.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": 400.0,
                "amount_min": 55.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Silicon",
        "unit": "UG",
        "fdc_ids": [1150],
        "recommendations": [],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Sodium",
        "unit": "G",
        "fdc_ids": [1093],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 1.5,
                "amount_min": 1.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 1.9,
                "amount_min": 1.2,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 2.2,
                "amount_min": 1.5,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 50,
                "age_min": 14,
                "amount_max": 2.3,
                "amount_min": 1.5,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 70,
                "age_min": 51,
                "amount_max": 2.3,
                "amount_min": 1.3,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 71,
                "amount_max": 2.3,
                "amount_min": 1.2,
                "dri_type": "AI",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Vanadium",
        "unit": "MG",
        "fdc_ids": [1155],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 1.8,
                "dri_type": "UL",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Zinc",
        "unit": "MG",
        "fdc_ids": [1095],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 7.0,
                "amount_min": 3.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 12.0,
                "amount_min": 5.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 23.0,
                "amount_min": 8.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 34.0,
                "amount_min": 11.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 34.0,
                "amount_min": 9.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 40.0,
                "amount_min": 11.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 40.0,
                "amount_min": 8.0,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Mineral"],
    },
    {
        "name": "Vitamin B1",
        "unit": "MG",
        "fdc_ids": [1165],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 0.5,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 0.6,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 0.9,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 1.2,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 1.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 1.1,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin B2",
        "unit": "MG",
        "fdc_ids": [1166],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 0.5,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 0.6,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 0.9,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 1.3,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 1.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 1.1,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin B3",
        "unit": "MG",
        "fdc_ids": [1167],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 10.0,
                "amount_min": 6.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 15.0,
                "amount_min": 8.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 20.0,
                "amount_min": 12.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 30.0,
                "amount_min": 16.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 30.0,
                "amount_min": 14.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 35.0,
                "amount_min": 16.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 35.0,
                "amount_min": 14.0,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin B5",
        "unit": "MG",
        "fdc_ids": [1170],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 2.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 3.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 4.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 5.0,
                "dri_type": "AI",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin B6",
        "unit": "MG",
        "fdc_ids": [1175],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 30.0,
                "amount_min": 0.5,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 40.0,
                "amount_min": 0.6,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 60.0,
                "amount_min": 1.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 80.0,
                "amount_min": 1.3,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 80.0,
                "amount_min": 1.2,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": 50,
                "age_min": 19,
                "amount_max": 100.0,
                "amount_min": 1.3,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": 100.0,
                "amount_min": 1.7,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": 100.0,
                "amount_min": 1.5,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin B7",
        "unit": "UG",
        "fdc_ids": [1176],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 8.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 12.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 20.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 25.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 30.0,
                "dri_type": "AI",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin B9",
        "unit": "UG",
        "fdc_ids": [1177, 1190],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 300.0,
                "amount_min": 150.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 400.0,
                "amount_min": 200.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 600.0,
                "amount_min": 300.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 800.0,
                "amount_min": 400.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 1000.0,
                "amount_min": 400.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin B12",
        "unit": "UG",
        "fdc_ids": [1178],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 0.9,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 1.2,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 1.8,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 2.4,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin A",
        "unit": "UG",
        "fdc_ids": [1104, 1106],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 600.0,
                "amount_min": 300.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 900.0,
                "amount_min": 400.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 1700.0,
                "amount_min": 600.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 2800.0,
                "amount_min": 900.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 2800.0,
                "amount_min": 700.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 3000.0,
                "amount_min": 900.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 3000.0,
                "amount_min": 700.0,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin C",
        "unit": "MG",
        "fdc_ids": [1162],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 400.0,
                "amount_min": 15.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 650.0,
                "amount_min": 25.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 1200.0,
                "amount_min": 45.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 1800.0,
                "amount_min": 75.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 1800.0,
                "amount_min": 65.0,
                "dri_type": "RDA",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 2000.0,
                "amount_min": 90.0,
                "dri_type": "RDA",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 2000.0,
                "amount_min": 75.0,
                "dri_type": "RDA",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin D",
        "unit": "UG",
        "fdc_ids": [1110, 1114],
        "recommendations": [
            {
                "age_max": 50,
                "age_min": 1,
                "amount_max": 50.0,
                "amount_min": 5.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 70,
                "age_min": 51,
                "amount_max": 50.0,
                "amount_min": 10.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 71,
                "amount_max": 50.0,
                "amount_min": 15.0,
                "dri_type": "AI",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin D2",
        "unit": "UG",
        "fdc_ids": [1111],
        "recommendations": [],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin D3",
        "unit": "UG",
        "fdc_ids": [1112],
        "recommendations": [],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin E",
        "unit": "MG",
        "fdc_ids": [1109],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 200.0,
                "amount_min": 6.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 300.0,
                "amount_min": 7.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 600.0,
                "amount_min": 11.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 800.0,
                "amount_min": 15.0,
                "dri_type": "RDA",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 1000.0,
                "amount_min": 15.0,
                "dri_type": "RDA",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Vitamin K",
        "unit": "UG",
        "fdc_ids": [1183, 1184, 1185],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 30.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 55.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 60.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 75.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 120.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 90.0,
                "dri_type": "AI",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Vitamin"],
    },
    {
        "name": "Alanine",
        "unit": "MG",
        "fdc_ids": [1222],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Arginine",
        "unit": "MG",
        "fdc_ids": [1220],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Aspartic acid",
        "unit": "MG",
        "fdc_ids": [1223],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Asparagine",
        "unit": "MG",
        "fdc_ids": [1231],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Cysteine",
        "unit": "MG",
        "fdc_ids": [1216, 1232],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Glutamic acid",
        "unit": "MG",
        "fdc_ids": [1224],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Glutamine",
        "unit": "MG",
        "fdc_ids": [1233],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Glycine",
        "unit": "MG",
        "fdc_ids": [1225],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Histidine",
        "unit": "MG",
        "fdc_ids": [1221],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 16.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 17.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 15.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 15.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 14.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 15.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Isoleucine",
        "unit": "MG",
        "fdc_ids": [1212],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 28.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 22.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 22.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 19.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 20.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Leucine",
        "unit": "MG",
        "fdc_ids": [1213],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 63.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 49.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 49.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 47.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 47.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 44.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 45.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Lysine",
        "unit": "MG",
        "fdc_ids": [1214],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 58.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 46.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 46.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 43.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 43.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 40.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 41.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Methionine",
        "unit": "MG",
        "fdc_ids": [1215],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Phenylalanine",
        "unit": "MG",
        "fdc_ids": [1217],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Proline",
        "unit": "MG",
        "fdc_ids": [1226],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Serine",
        "unit": "MG",
        "fdc_ids": [1227],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Threonine",
        "unit": "MG",
        "fdc_ids": [1211],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 32.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 24.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 24.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 22.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 22.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Tryptophan",
        "unit": "MG",
        "fdc_ids": [1210],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 8.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 6.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 6.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 6.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 6.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 5.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 5.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Tyrosine",
        "unit": "MG",
        "fdc_ids": [1218],
        "recommendations": [],
        "type": ["Micronutrient", "Amino acid"],
    },
    {
        "name": "Valine",
        "unit": "MG",
        "fdc_ids": [1219],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 37.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 28.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 28.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 27.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 27.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 24.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 25.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Amino acid", "Indispensable amino acid"],
    },
    {
        "name": "Saturated fatty acids",
        "unit": "G",
        "fdc_ids": [1258],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 0,
                "amount_max": None,
                "amount_min": None,
                "dri_type": "ALAP",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Fatty acid type"],
    },
    {
        "name": "Monounsaturated fatty acids",
        "unit": "G",
        "fdc_ids": [1292],
        "recommendations": [],
        "type": ["Micronutrient", "Fatty acid type"],
    },
    {
        "name": "Polyunsaturated fatty acids",
        "unit": "G",
        "fdc_ids": [1293],
        "recommendations": [],
        "type": ["Micronutrient", "Fatty acid type"],
    },
    {
        "name": "Trans fatty acids",
        "unit": "G",
        "fdc_ids": [1257],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 0,
                "amount_max": None,
                "amount_min": None,
                "dri_type": "ALAP",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Fatty acid type"],
    },
    {
        "name": "Cholesterol",
        "unit": "MG",
        "fdc_ids": [1253],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 0,
                "amount_max": None,
                "amount_min": None,
                "dri_type": "ALAP",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient"],
    },
    {
        "name": "Sugars",
        "unit": "G",
        "fdc_ids": [2000],
        "recommendations": [],
        "type": ["Micronutrient", "Carbohydrate"],
    },
    {
        "name": "Sugars (added)",
        "unit": "G",
        "fdc_ids": [1235],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 0,
                "amount_max": None,
                "amount_min": 25.0,
                "dri_type": "UL",
                "sex": "B",
            },
        ],
        "type": ["Micronutrient", "Carbohydrate"],
    },
    {
        "name": "alpha-Linolenic acid",
        "unit": "G",
        "fdc_ids": [1404],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 0,
                "amount_max": 1.2,
                "amount_min": 0.6,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 0.7,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 0.9,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 1.2,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 1.6,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 1.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 1.1,
                "dri_type": "AI",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Polyunsaturated fatty acid"],
        "energy": 9,
    },
    {
        "name": "Linoleic acid",
        "unit": "G",
        "fdc_ids": [1316],
        "recommendations": [
            {
                "age_max": None,
                "age_min": 0,
                "amount_max": 10.0,
                "amount_min": 5.0,
                "dri_type": "AMDR",
                "sex": "B",
            },
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 7.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 10.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 12.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 16.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 50,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 17.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": None,
                "amount_min": 14.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 10.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 11.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": 50,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 12.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 51,
                "amount_max": None,
                "amount_min": 11.0,
                "dri_type": "AI",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient", "Polyunsaturated fatty acid"],
        "energy": 9,
    },
    {
        "name": "Choline",
        "unit": "MG",
        "fdc_ids": [1180],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": 1000.0,
                "amount_min": 200.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": 1000.0,
                "amount_min": 250.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": 2000.0,
                "amount_min": 375.0,
                "dri_type": "AI",
                "sex": "B",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 3000.0,
                "amount_min": 550.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": 3000.0,
                "amount_min": 400.0,
                "dri_type": "AI",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 3500.0,
                "amount_min": 550.0,
                "dri_type": "AI",
                "sex": "M",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": 3500.0,
                "amount_min": 425.0,
                "dri_type": "AI",
                "sex": "F",
            },
        ],
        "type": ["Micronutrient"],
    },
    {
        "name": "Methionine + Cysteine",
        "unit": "MG",
        "fdc_ids": [],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 28.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 22.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 22.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 21.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 19.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 20.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Amino acid"],
        "components": ["Methionine", "Cysteine"],
    },
    {
        "name": "Phenylalanine + Tyrosine",
        "unit": "MG",
        "fdc_ids": [],
        "recommendations": [
            {
                "age_max": 3,
                "age_min": 1,
                "amount_max": None,
                "amount_min": 54.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 8,
                "age_min": 4,
                "amount_max": None,
                "amount_min": 41.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 41.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 13,
                "age_min": 9,
                "amount_max": None,
                "amount_min": 38.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 38.0,
                "dri_type": "RDA/KG",
                "sex": "M",
            },
            {
                "age_max": 18,
                "age_min": 14,
                "amount_max": None,
                "amount_min": 35.0,
                "dri_type": "RDA/KG",
                "sex": "F",
            },
            {
                "age_max": None,
                "age_min": 19,
                "amount_max": None,
                "amount_min": 36.0,
                "dri_type": "RDA/KG",
                "sex": "B",
            },
        ],
        "type": ["Amino acid"],
        "components": ["Phenylalanine", "Tyrosine"],
    },
]


# Mapping of nutrient's ID in the FDC database to the nutrient's name in
# this application.
FDC_TO_NUTRIENT = {}
for nutrient in FULL_NUTRIENT_DATA:
    for id_ in nutrient["fdc_ids"]:
        FDC_TO_NUTRIENT[id_] = nutrient["name"]


NUTRIENT_TYPES = set()
for nutrient in FULL_NUTRIENT_DATA:
    for type_ in nutrient["type"]:
        NUTRIENT_TYPES.add(type_)

NUTRIENT_TYPE_DISPLAY_NAME = {"Fatty acid type": "Lipid"}
