"""Recommendation data from:
    Institute of Medicine 2006.
    Dietary Reference Intakes: The Essential Guide to Nutrient
    Requirements.
    Washington, DC: The National Academies Press.
    https://doi.org/10.17226/11537
"""
recommendations = [
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 40.0,
        "amount_min": 30.0,
        "dri_type": "AMDR",
        "nutrient": "Lipid",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 4,
        "amount_max": 35.0,
        "amount_min": 25.0,
        "dri_type": "AMDR",
        "nutrient": "Lipid",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 35.0,
        "amount_min": 20.0,
        "dri_type": "AMDR",
        "nutrient": "Lipid",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 0,
        "amount_max": 10.0,
        "amount_min": 5.0,
        "dri_type": "AMDR",
        "nutrient": "Linoleic acid",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 0,
        "amount_max": 1.2,
        "amount_min": 0.6,
        "dri_type": "AMDR",
        "nutrient": "alpha-Linolenic acid",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 1,
        "amount_max": 65.0,
        "amount_min": 45.0,
        "dri_type": "AMDR",
        "nutrient": "Carbohydrate",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 130.0,
        "dri_type": "RDA",
        "nutrient": "Carbohydrate",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 20.0,
        "amount_min": 5.0,
        "dri_type": "AMDR",
        "nutrient": "Protein",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 4,
        "amount_max": 30.0,
        "amount_min": 10.0,
        "dri_type": "AMDR",
        "nutrient": "Protein",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 35.0,
        "amount_min": 10.0,
        "dri_type": "AMDR",
        "nutrient": "Protein",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 0,
        "amount_max": None,
        "amount_min": None,
        "dri_type": "ALAP",
        "nutrient": "Cholesterol",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 0,
        "amount_max": None,
        "amount_min": None,
        "dri_type": "ALAP",
        "nutrient": "Trans fatty acids",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 0,
        "amount_max": None,
        "amount_min": None,
        "dri_type": "ALAP",
        "nutrient": "Saturated fatty acids",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 0,
        "amount_max": None,
        "amount_min": 25.0,
        "dri_type": "UL",
        "nutrient": "Sugars (added)",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 14.0,
        "dri_type": "AIK",
        "nutrient": "Fiber",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 7.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 10.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 12.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 16.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "M",
    },
    {
        "age_max": 50,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 17.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": None,
        "amount_min": 14.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 10.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 11.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "F",
    },
    {
        "age_max": 50,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 12.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": None,
        "amount_min": 11.0,
        "dri_type": "AI",
        "nutrient": "Linoleic acid",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 0.7,
        "dri_type": "AI",
        "nutrient": "alpha-Linolenic acid",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 0.9,
        "dri_type": "AI",
        "nutrient": "alpha-Linolenic acid",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 1.2,
        "dri_type": "AI",
        "nutrient": "alpha-Linolenic acid",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 1.6,
        "dri_type": "AI",
        "nutrient": "alpha-Linolenic acid",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 1.0,
        "dri_type": "AI",
        "nutrient": "alpha-Linolenic acid",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 1.1,
        "dri_type": "AI",
        "nutrient": "alpha-Linolenic acid",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 1.05,
        "dri_type": "RDA/KG",
        "nutrient": "Protein",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 0.95,
        "dri_type": "RDA/KG",
        "nutrient": "Protein",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 0.85,
        "dri_type": "RDA/KG",
        "nutrient": "Protein",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 0.8,
        "dri_type": "RDA/KG",
        "nutrient": "Protein",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 1300.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 1700.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 2400.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 2100.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 3300.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 2300.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 3700.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 2700.0,
        "dri_type": "AI",
        "nutrient": "Water",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 600.0,
        "amount_min": 300.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin A",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 900.0,
        "amount_min": 400.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin A",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 1700.0,
        "amount_min": 600.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin A",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 2800.0,
        "amount_min": 900.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin A",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 2800.0,
        "amount_min": 700.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin A",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 3000.0,
        "amount_min": 900.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin A",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 3000.0,
        "amount_min": 700.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin A",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 30.0,
        "amount_min": 0.5,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 40.0,
        "amount_min": 0.6,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 60.0,
        "amount_min": 1.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 80.0,
        "amount_min": 1.3,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 80.0,
        "amount_min": 1.2,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "F",
    },
    {
        "age_max": 50,
        "age_min": 19,
        "amount_max": 100.0,
        "amount_min": 1.3,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": 100.0,
        "amount_min": 1.7,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": 100.0,
        "amount_min": 1.5,
        "dri_type": "RDA",
        "nutrient": "Vitamin B6",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 0.9,
        "dri_type": "RDA",
        "nutrient": "Vitamin B12",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 1.2,
        "dri_type": "RDA",
        "nutrient": "Vitamin B12",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 1.8,
        "dri_type": "RDA",
        "nutrient": "Vitamin B12",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 2.4,
        "dri_type": "RDA",
        "nutrient": "Vitamin B12",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 8.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B7",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 12.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B7",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 20.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B7",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 25.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B7",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 30.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B7",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 400.0,
        "amount_min": 15.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin C",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 650.0,
        "amount_min": 25.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin C",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 1200.0,
        "amount_min": 45.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin C",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 1800.0,
        "amount_min": 75.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin C",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 1800.0,
        "amount_min": 65.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin C",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 2000.0,
        "amount_min": 90.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin C",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 2000.0,
        "amount_min": 75.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin C",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 1000.0,
        "amount_min": 200.0,
        "dri_type": "AI",
        "nutrient": "Choline",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 1000.0,
        "amount_min": 250.0,
        "dri_type": "AI",
        "nutrient": "Choline",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 2000.0,
        "amount_min": 375.0,
        "dri_type": "AI",
        "nutrient": "Choline",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 3000.0,
        "amount_min": 550.0,
        "dri_type": "AI",
        "nutrient": "Choline",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 3000.0,
        "amount_min": 400.0,
        "dri_type": "AI",
        "nutrient": "Choline",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 3500.0,
        "amount_min": 550.0,
        "dri_type": "AI",
        "nutrient": "Choline",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 3500.0,
        "amount_min": 425.0,
        "dri_type": "AI",
        "nutrient": "Choline",
        "sex": "F",
    },
    {
        "age_max": 50,
        "age_min": 1,
        "amount_max": 50.0,
        "amount_min": 5.0,
        "dri_type": "AI",
        "nutrient": "Vitamin D",
        "sex": "B",
    },
    {
        "age_max": 70,
        "age_min": 51,
        "amount_max": 50.0,
        "amount_min": 10.0,
        "dri_type": "AI",
        "nutrient": "Vitamin D",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 71,
        "amount_max": 50.0,
        "amount_min": 15.0,
        "dri_type": "AI",
        "nutrient": "Vitamin D",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 200.0,
        "amount_min": 6.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin E",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 300.0,
        "amount_min": 7.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin E",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 600.0,
        "amount_min": 11.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin E",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 800.0,
        "amount_min": 15.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin E",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 1000.0,
        "amount_min": 15.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin E",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 300.0,
        "amount_min": 150.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B9",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 400.0,
        "amount_min": 200.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B9",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 600.0,
        "amount_min": 300.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B9",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 800.0,
        "amount_min": 400.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B9",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 1000.0,
        "amount_min": 400.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B9",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 30.0,
        "dri_type": "AI",
        "nutrient": "Vitamin K",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 55.0,
        "dri_type": "AI",
        "nutrient": "Vitamin K",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 60.0,
        "dri_type": "AI",
        "nutrient": "Vitamin K",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 75.0,
        "dri_type": "AI",
        "nutrient": "Vitamin K",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 120.0,
        "dri_type": "AI",
        "nutrient": "Vitamin K",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 90.0,
        "dri_type": "AI",
        "nutrient": "Vitamin K",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 10.0,
        "amount_min": 6.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B3",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 15.0,
        "amount_min": 8.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B3",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 20.0,
        "amount_min": 12.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B3",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 30.0,
        "amount_min": 16.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B3",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 30.0,
        "amount_min": 14.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B3",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 35.0,
        "amount_min": 16.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B3",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 35.0,
        "amount_min": 14.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B3",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 2.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B5",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 3.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B5",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 4.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B5",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 5.0,
        "dri_type": "AI",
        "nutrient": "Vitamin B5",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 0.5,
        "dri_type": "RDA",
        "nutrient": "Vitamin B2",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 0.6,
        "dri_type": "RDA",
        "nutrient": "Vitamin B2",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 0.9,
        "dri_type": "RDA",
        "nutrient": "Vitamin B2",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 1.3,
        "dri_type": "RDA",
        "nutrient": "Vitamin B2",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 1.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B2",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 1.1,
        "dri_type": "RDA",
        "nutrient": "Vitamin B2",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 0.5,
        "dri_type": "RDA",
        "nutrient": "Vitamin B1",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 0.6,
        "dri_type": "RDA",
        "nutrient": "Vitamin B1",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 0.9,
        "dri_type": "RDA",
        "nutrient": "Vitamin B1",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 1.2,
        "dri_type": "RDA",
        "nutrient": "Vitamin B1",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 1.0,
        "dri_type": "RDA",
        "nutrient": "Vitamin B1",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 1.1,
        "dri_type": "RDA",
        "nutrient": "Vitamin B1",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 2500.0,
        "amount_min": 500.0,
        "dri_type": "AI",
        "nutrient": "Calcium",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 2500.0,
        "amount_min": 800.0,
        "dri_type": "AI",
        "nutrient": "Calcium",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 9,
        "amount_max": 2500.0,
        "amount_min": 1300.0,
        "dri_type": "AI",
        "nutrient": "Calcium",
        "sex": "B",
    },
    {
        "age_max": 50,
        "age_min": 19,
        "amount_max": 2500.0,
        "amount_min": 1000.0,
        "dri_type": "AI",
        "nutrient": "Calcium",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": 2500.0,
        "amount_min": 1200.0,
        "dri_type": "AI",
        "nutrient": "Calcium",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 11.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 15.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 25.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "F",
    },
    {
        "age_max": 50,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 35.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 24.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "F",
    },
    {
        "age_max": 50,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 25.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": None,
        "amount_min": 30.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": None,
        "amount_min": 20.0,
        "dri_type": "AI",
        "nutrient": "Chromium",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 1000.0,
        "amount_min": 340.0,
        "dri_type": "RDA",
        "nutrient": "Copper",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 3000.0,
        "amount_min": 440.0,
        "dri_type": "RDA",
        "nutrient": "Copper",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 5000.0,
        "amount_min": 700.0,
        "dri_type": "RDA",
        "nutrient": "Copper",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 8000.0,
        "amount_min": 890.0,
        "dri_type": "RDA",
        "nutrient": "Copper",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 10000.0,
        "amount_min": 900.0,
        "dri_type": "RDA",
        "nutrient": "Copper",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 1.3,
        "amount_min": 0.7,
        "dri_type": "AI",
        "nutrient": "Fluoride",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 2.2,
        "amount_min": 1.0,
        "dri_type": "AI",
        "nutrient": "Fluoride",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 10.0,
        "amount_min": 2.0,
        "dri_type": "AI",
        "nutrient": "Fluoride",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 10.0,
        "amount_min": 3.0,
        "dri_type": "AI",
        "nutrient": "Fluoride",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": 10.0,
        "amount_min": 3.0,
        "dri_type": "AI",
        "nutrient": "Fluoride",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 10.0,
        "amount_min": 4.0,
        "dri_type": "AI",
        "nutrient": "Fluoride",
        "sex": "M",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 200.0,
        "amount_min": 90.0,
        "dri_type": "RDA",
        "nutrient": "Iodine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 300.0,
        "amount_min": 90.0,
        "dri_type": "RDA",
        "nutrient": "Iodine",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 600.0,
        "amount_min": 120.0,
        "dri_type": "RDA",
        "nutrient": "Iodine",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 900.0,
        "amount_min": 150.0,
        "dri_type": "RDA",
        "nutrient": "Iodine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 1100.0,
        "amount_min": 150.0,
        "dri_type": "RDA",
        "nutrient": "Iodine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 40.0,
        "amount_min": 7.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 40.0,
        "amount_min": 10.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 40.0,
        "amount_min": 8.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 45.0,
        "amount_min": 11.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 45.0,
        "amount_min": 15.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "F",
    },
    {
        "age_max": 50,
        "age_min": 19,
        "amount_max": 45.0,
        "amount_min": 8.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "M",
    },
    {
        "age_max": 50,
        "age_min": 19,
        "amount_max": 45.0,
        "amount_min": 18.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 51,
        "amount_max": 45.0,
        "amount_min": 8.0,
        "dri_type": "RDA",
        "nutrient": "Iron",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 80.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 130.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 240.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 410.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 360.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "F",
    },
    {
        "age_max": 30,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 400.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "M",
    },
    {
        "age_max": 30,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 310.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 31,
        "amount_max": None,
        "amount_min": 420.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 31,
        "amount_max": None,
        "amount_min": 320.0,
        "dri_type": "RDA",
        "nutrient": "Magnesium",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 2.0,
        "amount_min": 1.2,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 3.0,
        "amount_min": 1.5,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 6.0,
        "amount_min": 1.9,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 6.0,
        "amount_min": 1.6,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 9.0,
        "amount_min": 2.2,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 9.0,
        "amount_min": 1.6,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 11.0,
        "amount_min": 2.3,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 11.0,
        "amount_min": 1.8,
        "dri_type": "AI",
        "nutrient": "Manganese",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 300.0,
        "amount_min": 17.0,
        "dri_type": "RDA",
        "nutrient": "Molybdenum",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 600.0,
        "amount_min": 22.0,
        "dri_type": "RDA",
        "nutrient": "Molybdenum",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 1100.0,
        "amount_min": 34.0,
        "dri_type": "RDA",
        "nutrient": "Molybdenum",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 1700.0,
        "amount_min": 43.0,
        "dri_type": "RDA",
        "nutrient": "Molybdenum",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 2000.0,
        "amount_min": 45.0,
        "dri_type": "RDA",
        "nutrient": "Molybdenum",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 3000.0,
        "amount_min": 460.0,
        "dri_type": "RDA",
        "nutrient": "Phosphorus",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 3000.0,
        "amount_min": 500.0,
        "dri_type": "RDA",
        "nutrient": "Phosphorus",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 9,
        "amount_max": 4000.0,
        "amount_min": 1250.0,
        "dri_type": "RDA",
        "nutrient": "Phosphorus",
        "sex": "B",
    },
    {
        "age_max": 70,
        "age_min": 19,
        "amount_max": 4000.0,
        "amount_min": 700.0,
        "dri_type": "RDA",
        "nutrient": "Phosphorus",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 71,
        "amount_max": 3000.0,
        "amount_min": 700.0,
        "dri_type": "RDA",
        "nutrient": "Phosphorus",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 3.0,
        "dri_type": "AI",
        "nutrient": "Potassium",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 3.8,
        "dri_type": "AI",
        "nutrient": "Potassium",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 4.5,
        "dri_type": "AI",
        "nutrient": "Potassium",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 4.7,
        "dri_type": "AI",
        "nutrient": "Potassium",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 90.0,
        "amount_min": 20.0,
        "dri_type": "RDA",
        "nutrient": "Selenium",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 150.0,
        "amount_min": 30.0,
        "dri_type": "RDA",
        "nutrient": "Selenium",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 280.0,
        "amount_min": 40.0,
        "dri_type": "RDA",
        "nutrient": "Selenium",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": 400.0,
        "amount_min": 55.0,
        "dri_type": "RDA",
        "nutrient": "Selenium",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 1.5,
        "amount_min": 1.0,
        "dri_type": "AI",
        "nutrient": "Sodium",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 1.9,
        "amount_min": 1.2,
        "dri_type": "AI",
        "nutrient": "Sodium",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 2.2,
        "amount_min": 1.5,
        "dri_type": "AI",
        "nutrient": "Sodium",
        "sex": "B",
    },
    {
        "age_max": 50,
        "age_min": 14,
        "amount_max": 2.3,
        "amount_min": 1.5,
        "dri_type": "AI",
        "nutrient": "Sodium",
        "sex": "B",
    },
    {
        "age_max": 70,
        "age_min": 51,
        "amount_max": 2.3,
        "amount_min": 1.3,
        "dri_type": "AI",
        "nutrient": "Sodium",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 71,
        "amount_max": 2.3,
        "amount_min": 1.2,
        "dri_type": "AI",
        "nutrient": "Sodium",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 2.3,
        "amount_min": 1.5,
        "dri_type": "AI",
        "nutrient": "Chlorine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 2.9,
        "amount_min": 1.9,
        "dri_type": "AI",
        "nutrient": "Chlorine",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 3.4,
        "amount_min": 2.3,
        "dri_type": "AI",
        "nutrient": "Chlorine",
        "sex": "B",
    },
    {
        "age_max": 50,
        "age_min": 14,
        "amount_max": 3.6,
        "amount_min": 2.3,
        "dri_type": "AI",
        "nutrient": "Chlorine",
        "sex": "B",
    },
    {
        "age_max": 70,
        "age_min": 51,
        "amount_max": 3.6,
        "amount_min": 2.0,
        "dri_type": "AI",
        "nutrient": "Chlorine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 71,
        "amount_max": 3.6,
        "amount_min": 1.8,
        "dri_type": "AI",
        "nutrient": "Chlorine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": 7.0,
        "amount_min": 3.0,
        "dri_type": "RDA",
        "nutrient": "Zinc",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": 12.0,
        "amount_min": 5.0,
        "dri_type": "RDA",
        "nutrient": "Zinc",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": 23.0,
        "amount_min": 8.0,
        "dri_type": "RDA",
        "nutrient": "Zinc",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 34.0,
        "amount_min": 11.0,
        "dri_type": "RDA",
        "nutrient": "Zinc",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": 34.0,
        "amount_min": 9.0,
        "dri_type": "RDA",
        "nutrient": "Zinc",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 40.0,
        "amount_min": 11.0,
        "dri_type": "RDA",
        "nutrient": "Zinc",
        "sex": "M",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": 40.0,
        "amount_min": 8.0,
        "dri_type": "RDA",
        "nutrient": "Zinc",
        "sex": "F",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 3.0,
        "dri_type": "UL",
        "nutrient": "Boron",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 6.0,
        "dri_type": "UL",
        "nutrient": "Boron",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 11.0,
        "dri_type": "UL",
        "nutrient": "Boron",
        "sex": "B",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 17.0,
        "dri_type": "UL",
        "nutrient": "Boron",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 20.0,
        "dri_type": "UL",
        "nutrient": "Boron",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 0.2,
        "dri_type": "UL",
        "nutrient": "Nickel",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 0.3,
        "dri_type": "UL",
        "nutrient": "Nickel",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 0.6,
        "dri_type": "UL",
        "nutrient": "Nickel",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 1.0,
        "dri_type": "UL",
        "nutrient": "Nickel",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 1.8,
        "dri_type": "UL",
        "nutrient": "Vanadium",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "RDA/KG",
        "nutrient": "Histidine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 28.0,
        "dri_type": "RDA/KG",
        "nutrient": "Isoleucine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 63.0,
        "dri_type": "RDA/KG",
        "nutrient": "Leucine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 58.0,
        "dri_type": "RDA/KG",
        "nutrient": "Lysine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 28.0,
        "dri_type": "RDA/KG",
        "nutrient": "Methionine + Cysteine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 54.0,
        "dri_type": "RDA/KG",
        "nutrient": "Phenylalanine + Tyrosine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 32.0,
        "dri_type": "RDA/KG",
        "nutrient": "Threonine",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 8.0,
        "dri_type": "RDA/KG",
        "nutrient": "Tryptophan",
        "sex": "B",
    },
    {
        "age_max": 3,
        "age_min": 1,
        "amount_max": None,
        "amount_min": 37.0,
        "dri_type": "RDA/KG",
        "nutrient": "Valine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 16.0,
        "dri_type": "RDA/KG",
        "nutrient": "Histidine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 22.0,
        "dri_type": "RDA/KG",
        "nutrient": "Isoleucine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 49.0,
        "dri_type": "RDA/KG",
        "nutrient": "Leucine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 46.0,
        "dri_type": "RDA/KG",
        "nutrient": "Lysine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 22.0,
        "dri_type": "RDA/KG",
        "nutrient": "Methionine + Cysteine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 41.0,
        "dri_type": "RDA/KG",
        "nutrient": "Phenylalanine + Tyrosine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 24.0,
        "dri_type": "RDA/KG",
        "nutrient": "Threonine",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 6.0,
        "dri_type": "RDA/KG",
        "nutrient": "Tryptophan",
        "sex": "B",
    },
    {
        "age_max": 8,
        "age_min": 4,
        "amount_max": None,
        "amount_min": 28.0,
        "dri_type": "RDA/KG",
        "nutrient": "Valine",
        "sex": "B",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 17.0,
        "dri_type": "RDA/KG",
        "nutrient": "Histidine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 22.0,
        "dri_type": "RDA/KG",
        "nutrient": "Isoleucine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 49.0,
        "dri_type": "RDA/KG",
        "nutrient": "Leucine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 46.0,
        "dri_type": "RDA/KG",
        "nutrient": "Lysine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 22.0,
        "dri_type": "RDA/KG",
        "nutrient": "Methionine + Cysteine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 41.0,
        "dri_type": "RDA/KG",
        "nutrient": "Phenylalanine + Tyrosine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 24.0,
        "dri_type": "RDA/KG",
        "nutrient": "Threonine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 6.0,
        "dri_type": "RDA/KG",
        "nutrient": "Tryptophan",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 28.0,
        "dri_type": "RDA/KG",
        "nutrient": "Valine",
        "sex": "M",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 15.0,
        "dri_type": "RDA/KG",
        "nutrient": "Histidine",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "RDA/KG",
        "nutrient": "Isoleucine",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 47.0,
        "dri_type": "RDA/KG",
        "nutrient": "Leucine",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 43.0,
        "dri_type": "RDA/KG",
        "nutrient": "Lysine",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "RDA/KG",
        "nutrient": "Methionine + Cysteine",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 38.0,
        "dri_type": "RDA/KG",
        "nutrient": "Phenylalanine + Tyrosine",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 22.0,
        "dri_type": "RDA/KG",
        "nutrient": "Threonine",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 6.0,
        "dri_type": "RDA/KG",
        "nutrient": "Tryptophan",
        "sex": "F",
    },
    {
        "age_max": 13,
        "age_min": 9,
        "amount_max": None,
        "amount_min": 27.0,
        "dri_type": "RDA/KG",
        "nutrient": "Valine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 15.0,
        "dri_type": "RDA/KG",
        "nutrient": "Histidine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "RDA/KG",
        "nutrient": "Isoleucine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 47.0,
        "dri_type": "RDA/KG",
        "nutrient": "Leucine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 43.0,
        "dri_type": "RDA/KG",
        "nutrient": "Lysine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "RDA/KG",
        "nutrient": "Methionine + Cysteine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 38.0,
        "dri_type": "RDA/KG",
        "nutrient": "Phenylalanine + Tyrosine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 22.0,
        "dri_type": "RDA/KG",
        "nutrient": "Threonine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 6.0,
        "dri_type": "RDA/KG",
        "nutrient": "Tryptophan",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 27.0,
        "dri_type": "RDA/KG",
        "nutrient": "Valine",
        "sex": "M",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 14.0,
        "dri_type": "RDA/KG",
        "nutrient": "Histidine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 19.0,
        "dri_type": "RDA/KG",
        "nutrient": "Isoleucine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 44.0,
        "dri_type": "RDA/KG",
        "nutrient": "Leucine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 40.0,
        "dri_type": "RDA/KG",
        "nutrient": "Lysine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 19.0,
        "dri_type": "RDA/KG",
        "nutrient": "Methionine + Cysteine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 35.0,
        "dri_type": "RDA/KG",
        "nutrient": "Phenylalanine + Tyrosine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "RDA/KG",
        "nutrient": "Threonine",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 5.0,
        "dri_type": "RDA/KG",
        "nutrient": "Tryptophan",
        "sex": "F",
    },
    {
        "age_max": 18,
        "age_min": 14,
        "amount_max": None,
        "amount_min": 24.0,
        "dri_type": "RDA/KG",
        "nutrient": "Valine",
        "sex": "F",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 15.0,
        "dri_type": "RDA/KG",
        "nutrient": "Histidine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 20.0,
        "dri_type": "RDA/KG",
        "nutrient": "Isoleucine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 45.0,
        "dri_type": "RDA/KG",
        "nutrient": "Leucine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 41.0,
        "dri_type": "RDA/KG",
        "nutrient": "Lysine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 20.0,
        "dri_type": "RDA/KG",
        "nutrient": "Methionine + Cysteine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 36.0,
        "dri_type": "RDA/KG",
        "nutrient": "Phenylalanine + Tyrosine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 21.0,
        "dri_type": "RDA/KG",
        "nutrient": "Threonine",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 5.0,
        "dri_type": "RDA/KG",
        "nutrient": "Tryptophan",
        "sex": "B",
    },
    {
        "age_max": None,
        "age_min": 19,
        "amount_max": None,
        "amount_min": 25.0,
        "dri_type": "RDA/KG",
        "nutrient": "Valine",
        "sex": "B",
    },
]
