services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: food_hub_app
    command: >
      bash -c "poetry run python src/food_hub/manage.py migrate
      && poetry run python src/food_hub/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
