"""Migration setting the choices for nutrient model's unit field."""
# Generated by Django 4.1.3 on 2022-11-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KCAL", "calories"),
                    ("G", "grams"),
                    ("MG", "milligrams"),
                    ("UG", "micrograms"),
                    ("IU", "IU"),
                ],
                max_length=10,
            ),
        ),
    ]
