# Generated by Django 4.1.4 on 2023-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial_model_setup"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredientnutrient",
            name="unique_ingredient_nutrient",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="dataset",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="external_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("data_source", "external_id"),
                name="unique_ingredient_data_source_and_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientnutrient",
            constraint=models.UniqueConstraint(
                models.F("ingredient"),
                models.F("nutrient"),
                name="unique_ingredient_intermediate_nutrient",
            ),
        ),
    ]
