"""Data migration loading nutrient data."""
# Generated by Django 4.1.3 on 2022-11-28 09:18
import csv
import io
import os
from typing import Union

from django.conf import settings
from django.db import migrations
from util import open_or_pass

UNIT_CONVERSION = {
    "MCG_RE": "UG",
    "MG_GAE": "MG",
    "MG_ATE": "MG",
}

IGNORED_UNITS = {"PH", "UMOL_TE", "SP_GR"}


def parse_nutrient_csv(nutrient_model, file: Union[str, os.PathLike, io.IOBase]):
    """Read and parse FDC nutrient csv file.

    Parameters
    ----------
    nutrient_model
        The class implementing the nutrient model

    file
        File or path to the file containing nutrient data.

    """
    nutrient_list = []
    with open_or_pass(file, newline="") as f:
        reader = csv.DictReader(f)
        for nutrient_record in reader:

            # Unit parsing
            unit = nutrient_record.get("unit_name")
            if unit in IGNORED_UNITS:
                continue
            unit = UNIT_CONVERSION.get(unit) or unit

            nutrient = nutrient_model()
            nutrient.unit = unit
            nutrient.name = nutrient_record.get("name")
            nutrient.fdc_id = int(nutrient_record.get("id"))

            nutrient_list.append(nutrient)
    nutrient_model.objects.bulk_create(nutrient_list)


def parse_nutrients(apps, schema_editor):
    """Load data from nutrient csv"""
    Nutrient = apps.get_model("main", "Nutrient")
    parse_nutrient_csv(Nutrient, settings.NUTRIENT_FILE)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial_squashed"),
    ]

    operations = [migrations.RunPython(parse_nutrients)]
