"""IntakeRecommendation model setup."""
# Generated by Django 4.1.4 on 2023-05-09 12:19

import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_ingredientnutrient_unique_ingredient_nutrient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dri_type",
                    models.CharField(
                        choices=[
                            ("AI", "AI/UL"),
                            ("AIK", "AI-KCAL"),
                            ("AMDR", "AMDR"),
                            ("RDA", "RDA/UL"),
                            ("UL", "UL"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("B", "Both"), ("F", "Female"), ("M", "Male")],
                        max_length=1,
                    ),
                ),
                ("age_min", models.PositiveIntegerField()),
                ("age_max", models.PositiveIntegerField(null=True)),
                ("amount_min", models.FloatField()),
                ("amount_max", models.FloatField(null=True)),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="main.nutrient",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="intakerecommendation",
            name="amount_min",
            field=models.FloatField(
                help_text="Use of the amount fields differs depending on the selected"
                " <em>dri_type</em>.</br>AMDR - <em>amount_min</em> and"
                " <em>amount_max</em> are the lower and the upper limits of"
                " the range respectively.</br>AI/UL and RDA/UL - "
                "<em>amount_min</em> is the RDA or AI value."
                " <em>amount_max</em> is the UL value (if available).</br>UL"
                " and AIK - use only <em>amount_min</em>."
            ),
        ),
        migrations.AddConstraint(
            model_name="intakerecommendation",
            constraint=models.CheckConstraint(
                check=django.db.models.lookups.LessThanOrEqual(
                    models.F("age_min"), models.F("age_max")
                ),
                name="recommendation_age_min_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="intakerecommendation",
            constraint=models.CheckConstraint(
                check=django.db.models.lookups.LessThanOrEqual(
                    models.F("amount_min"), models.F("amount_max")
                ),
                name="recommendation_amount_min_max",
            ),
        ),
    ]
