"""
Renamed IngredientNutrients to IngredientNutrient and added the dataset
column to the Ingredient table.
"""
# Generated by Django 4.1.3 on 2022-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_nutrient_data"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IngredientNutrients",
            new_name="IngredientNutrient",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="dataset",
            field=models.CharField(max_length=50),
        ),
    ]
