"""Data migration loading ingredient data.

### NOTE ###

This migration only loads records from the SR Legacy Foods dataset.
"""
# Generated by Django 4.1.3 on 2022-11-28 21:10


from django.conf import settings
from django.db import migrations
from util.parse_fdc_data import parse_food_csv


def parse_ingredients(apps, schema_editor):
    """Load data from food csv (SR Legacy Food only)"""
    Ingredient = apps.get_model("main", "Ingredient")
    parse_food_csv(Ingredient, settings.FOOD_FILE, source_filter=["sr_legacy_food"])


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_ingredientnutrients_ingredientnutrient_and_more"),
    ]

    operations = [migrations.RunPython(parse_ingredients)]
