# Generated by Django 4.1.4 on 2023-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_intakerecommendation_amount_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakerecommendation",
            name="dri_type",
            field=models.CharField(
                choices=[
                    ("AI", "AI/UL"),
                    ("AIK", "AI-KCAL"),
                    ("AI/KG", "AI/KG"),
                    ("ALAP", "As Low As Possible"),
                    ("AMDR", "AMDR"),
                    ("RDA", "RDA/UL"),
                    ("RDA/KG", "RDA/KG"),
                    ("UL", "UL"),
                ],
                max_length=6,
            ),
        ),
    ]
