# Generated by Django 4.1.4 on 2023-05-12 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_intakerecommendation_dri_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakerecommendation",
            name="nutrient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="recommendations",
                to="main.nutrient",
            ),
        ),
    ]
