"""
Apply a unique together constraint to nutrient and ingredient fields
to the IngredientNutrient model.
"""
# Generated by Django 4.1.3 on 2022-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_ingredient_data"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredientnutrient",
            constraint=models.UniqueConstraint(
                models.F("ingredient"),
                models.F("nutrient"),
                name="unique_ingredient_nutrient",
            ),
        ),
    ]
