"""Data migration loading ingredient nutrient data.

### NOTE ###
This is a very slow migration. The food_nutrient.csv is ~ 1.5 GB.
"""
# Generated by Django 4.1.3 on 2022-11-29 13:57

from django.conf import settings
from django.db import migrations
from util.parse_fdc_data import parse_food_nutrient_csv


def parse_ingredient_nutrients(apps, schema_editor):
    """Load data from food csv (SR Legacy Food only)"""
    IngredientNutrient = apps.get_model("main", "IngredientNutrient")
    Ingredient = apps.get_model("main", "Ingredient")
    Nutrient = apps.get_model("main", "Nutrient")

    parse_food_nutrient_csv(
        settings.FOOD_NUTRIENT_FILE,
        ingredient_nutrient_class=IngredientNutrient,
        ingredient_class=Ingredient,
        nutrient_class=Nutrient,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_ingredientnutrient_amount"),
    ]

    operations = [migrations.RunPython(parse_ingredient_nutrients)]
