# Generated by Django 4.1.4 on 2023-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0007_intakerecommendation_recommendation_unique_demographic_and_type",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="intakerecommendation",
            name="recommendation_unique_demographic_and_type",
        ),
        migrations.AddConstraint(
            model_name="intakerecommendation",
            constraint=models.UniqueConstraint(
                fields=("sex", "age_min", "age_max", "dri_type", "nutrient"),
                name="recommendation_unique_demographic_nutrient_and_type",
            ),
        ),
    ]
