"""Set IngredientNutrient ingredient field's related name to 'nutrients'"""
# Generated by Django 4.1.3 on 2022-12-01 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_ingredient_nutrient_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientnutrient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrients",
                to="main.ingredient",
            ),
        ),
    ]
