# Generated by Django 4.1.4 on 2023-05-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0008_remove_intakerecommendation_recommendation_unique_demographic_and_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NutrientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="nutrient",
            name="type",
            field=models.ManyToManyField(
                related_name="nutrients", to="main.nutrienttype"
            ),
        ),
    ]
