# Generated by Django 4.1.4 on 2023-05-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_nutrienttype_nutrient_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nutrient",
            old_name="type",
            new_name="types",
        ),
    ]
