"""Meal and MealComponent models."""
# Generated by Django 4.1.4 on 2022-12-07 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("main", "0010_meal_mealcomponent_mealcomponentingredient_and_more"),
        ("main", "0011_meal_user_mealcomponent_user"),
        ("main", "0012_alter_meal_date"),
        ("main", "0013_mealcomponent_final_mass"),
        ("main", "0014_rename_final_mass_mealcomponent_final_weight"),
    ]

    dependencies = [
        ("main", "0009_alter_ingredientnutrient_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MealComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MealComponentIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.ingredient",
                    ),
                ),
                (
                    "meal_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="main.mealcomponent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealComponentAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.mealcomponent",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="main.meal",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mealcomponentingredient",
            constraint=models.UniqueConstraint(
                models.F("meal_component"),
                models.F("ingredient"),
                name="unique_meal_component_ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealcomponentamount",
            constraint=models.UniqueConstraint(
                models.F("meal"), models.F("component"), name="unique_meal_component"
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mealcomponent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_components",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="mealcomponent",
            name="final_weight",
            field=models.FloatField(default=100),
        ),
    ]
