# Generated by Django 4.1.4 on 2023-05-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_rename_type_nutrient_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutrientEnergy",
            fields=[
                (
                    "nutrient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="energy",
                        serialize=False,
                        to="main.nutrient",
                    ),
                ),
                ("amount", models.FloatField()),
            ],
        ),
    ]
