# Generated by Django 4.1.3 on 2022-12-05 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_meal_user_mealcomponent_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
