# Generated by Django 4.1.4 on 2023-05-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_nutrientenergy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutrientenergy",
            options={"verbose_name_plural": "Nutrient energies"},
        ),
    ]
