# Generated by Django 4.1.4 on 2023-05-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_nutrientenergy_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="intakerecommendation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("age_max__isnull", True)),
                fields=("sex", "age_min", "dri_type", "nutrient"),
                name="recommendation_unique_demographic_nutrient_and_type_max_age_null",
            ),
        ),
    ]
