# Generated by Django 4.1.4 on 2023-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0013_intakerecommendation_recommendation_unique_demographic_nutrient_and_type_max_age_null",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrienttype",
            name="displayed_name",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
