"""
Migration that added energy_requirement and the missing weight column
to the profile table, and changed other columns to non-nullable.
"""
# Generated by Django 4.1.4 on 2023-03-29 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_profile_alter_mealcomponent_final_weight_squash"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="energy_requirement",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="weight",
            field=models.PositiveIntegerField(default=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("S", "Sedentary"),
                    ("LA", "Low Active"),
                    ("A", "Active"),
                    ("VA", "Very Active"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.PositiveIntegerField(default=175),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
