# Generated by Django 4.1.4 on 2023-06-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_intakerecommendation_amount_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakerecommendation",
            name="nutrient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="main.nutrient",
            ),
        ),
    ]
