"""
Renames `fdc_id` column to `external_id` in both Nutrient and Ingredient
table and creates a table for storing food data sources.
"""
# Generated by Django 4.1.4 on 2023-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_profile_energy_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="fdc_id",
            new_name="external_id",
        ),
        migrations.RenameField(
            model_name="nutrient",
            old_name="fdc_id",
            new_name="external_id",
        ),
    ]
