"""
Data migration creating an FDC food data source record.
"""
# Generated by Django 4.1.4 on 2023-04-04 16:18

from django.db import migrations


def create_fdc_data_source(apps, _):
    """Create a FoodDataSource record for USDA's Food Data Central."""
    FoodDataSource = apps.get_model("main", "FoodDataSource")
    FoodDataSource.objects.create(name="FDC")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_fooddatasource_rename_fdc_id_ingredient_external_id_and_more"),
    ]

    operations = [migrations.RunPython(create_fdc_data_source)]
