# Generated by Django 4.1.4 on 2023-04-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_fooddatasource_data_create_FDC_record_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="data_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.fooddatasource",
            ),
        ),
        migrations.AddField(
            model_name="nutrient",
            name="data_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.fooddatasource",
            ),
        ),
    ]
