"""
Data migration setting existing Nutrient and Ingredient model's
data source fields to FDC data source.

Only updates entries where data source is `None`
"""
# Generated by Django 4.1.4 on 2023-04-06 14:07

from django.db import migrations


def update_existing_null_data_sources_to_fdc(apps, _):
    """
    Update the data source column null entries for nutrient and
    ingredient tables to FDC.
    """

    FDC_ds = apps.get_model("main", "FoodDataSource").objects.get(name="FDC")
    Nutrient = apps.get_model("main", "Nutrient")
    Nutrient.objects.filter(data_source=None).update(data_source=FDC_ds)
    Ingredient = apps.get_model("main", "Ingredient")
    Ingredient.objects.filter(data_source=None).update(data_source=FDC_ds)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_ingredient_data_source_nutrient_data_source"),
    ]

    operations = [migrations.RunPython(update_existing_null_data_sources_to_fdc)]
