"""Change FoodDataSource name field to have a unique constraint."""
# Generated by Django 4.1.4 on 2023-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_ingredient_and_nutrient_fdc_datasource_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooddatasource",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
