# Generated by Django 4.1.4 on 2023-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_internalnutrient_nutrient_internal_nutrient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalnutrient",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
