"""
Renames internal nutrient to intermediate nutrient, creates
intermediate ingredient nutrient to later replace ingredient nutrient
and adds the intermediate nutrient field to the ingredient model.
"""
# Generated by Django 4.1.4 on 2023-04-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_internalnutrient_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InternalNutrient",
            new_name="IntermediateNutrient",
        ),
        migrations.CreateModel(
            name="IntermediateIngredientNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.ingredient",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.intermediatenutrient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingredient",
            name="intermediate_nutrients",
            field=models.ManyToManyField(
                through="main.IntermediateIngredientNutrient",
                to="main.intermediatenutrient",
            ),
        ),
        migrations.AddConstraint(
            model_name="intermediateingredientnutrient",
            constraint=models.UniqueConstraint(
                models.F("ingredient"),
                models.F("nutrient"),
                name="unique_ingredient_intermediate_nutrient",
            ),
        ),
    ]
