"""Adds a unit field to intermediate nutrient model."""
# Generated by Django 4.1.4 on 2023-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_rename_internalnutrient_intermediatenutrient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediatenutrient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KCAL", "calories"),
                    ("G", "grams"),
                    ("MG", "milligrams"),
                    ("UG", "micrograms"),
                    ("IU", "IU"),
                ],
                default="UG",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
