"""
Migration replacing the old nutrient model with the new model
(formerly IntermediateNutrient). Removes Nutrient and IngredientNutrient
models, renames IntermediateNutrient to Nutrient and
IntermediateIngredientNutrient to IngredientNutrient, and renames
ingredient's intermediate_nutrients field to nutrients.

Additionally, removes International Unit from nutrient unit choices
"""
# Generated by Django 4.1.4 on 2023-04-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_nutrient_to_intermediate_nutrient_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutrient",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="nutrient",
            name="internal_nutrient",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="intermediate_nutrients",
            new_name="nutrients",
        ),
        migrations.DeleteModel(
            name="IngredientNutrient",
        ),
        migrations.DeleteModel(
            name="Nutrient",
        ),
        migrations.RenameModel(
            old_name="IntermediateNutrient",
            new_name="Nutrient",
        ),
        migrations.RenameModel(
            old_name="IntermediateIngredientNutrient",
            new_name="IngredientNutrient",
        ),
        migrations.AlterField(
            model_name="nutrient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("KCAL", "calories"),
                    ("G", "grams"),
                    ("MG", "milligrams"),
                    ("UG", "micrograms"),
                ],
                max_length=10,
            ),
        ),
    ]
